spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fileserver?userUnicode=true?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&userSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
file-server:
  root-directory: E:/file/
